name: contact_objectbox
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  objectbox: ^2.5.1
  path_provider: ^2.1.3
  path_to_regexp: ^0.4.0
  objectbox_flutter_libs: any
  flutter_riverpod: ^2.5.1
  riverpod_generator: ^2.4.0
  riverpod_annotation: ^2.3.5
  image_picker: ^1.1.1
  fluttertoast: ^8.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.9
  objectbox_generator: any

flutter:
  uses-material-design: true
